const DB_NAME="cander_music_db", TRACKS="tracks", USERS="users";
let db, audio=new Audio(), currentId=null, currentList=[], currentIndex=-1, currentObjectUrl=null;
const page=location.pathname.split("/").pop()||"index.html";
const pageName=page==="library.html"?"library":page==="favorites.html"?"favorites":page==="about.html"?"about":"home";

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(TRACKS))d.createObjectStore(TRACKS,{keyPath:"id"});if(!d.objectStoreNames.contains(USERS))d.createObjectStore(USERS,{keyPath:"email"})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function allTracks(){return new Promise((res,rej)=>{const r=db.transaction(TRACKS).objectStore(TRACKS).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function saveTrack(t){return new Promise((res,rej)=>{const r=db.transaction(TRACKS,"readwrite").objectStore(TRACKS).put(t);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function deleteTrack(id){return new Promise((res,rej)=>{const r=db.transaction(TRACKS,"readwrite").objectStore(TRACKS).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function getUser(email){return new Promise((res,rej)=>{const r=db.transaction(USERS).objectStore(USERS).get(email);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function saveUser(u){return new Promise((res,rej)=>{const r=db.transaction(USERS,"readwrite").objectStore(USERS).put(u);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function cover(title){const c=document.createElement("canvas");c.width=c.height=500;const x=c.getContext("2d"),g=x.createLinearGradient(0,0,500,500);g.addColorStop(0,"#ff2f7d");g.addColorStop(1,"#201328");x.fillStyle=g;x.fillRect(0,0,500,500);x.fillStyle="rgba(255,255,255,.18)";x.font="bold 250px Arial";x.fillText("♪",145,350);x.fillStyle="white";x.font="bold 30px Arial";x.fillText((title||"Track").slice(0,24),25,455);return c.toDataURL("image/jpeg",.82)}
function getSession(){try{return JSON.parse(localStorage.getItem("cander_session")||"null")}catch{return null}}
function setSession(user){if(user)localStorage.setItem("cander_session",JSON.stringify({email:user.email,name:user.name}));else localStorage.removeItem("cander_session");updateAccountUI()}
async function sha256(value){const data=new TextEncoder().encode(value),hash=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function validGmail(email){return /^[A-Z0-9._%+-]+@gmail\.com$/i.test(email)}
function layout(content){
 document.querySelector("#app").innerHTML=`<aside class="sidebar"><div class="logo">Cander<span>Music</span></div><nav class="nav"><a href="index.html" class="${pageName==="home"?"active":""}"><span class="icon">⌂</span><span>Главная</span></a><a href="library.html" class="${pageName==="library"?"active":""}"><span class="icon">♫</span><span>Все песни</span></a><a href="favorites.html" class="${pageName==="favorites"?"active":""}"><span class="icon">♥</span><span>Избранное</span></a><a href="about.html" class="${pageName==="about"?"active":""}"><span class="icon">⚙</span><span>О проекте</span></a></nav></aside>
 <main class="main"><div class="topbar"><input id="search" class="search" placeholder="Поиск по своей музыке..."><div id="account"></div></div>${content}</main>
 <div class="player"><div class="now"><img id="nowCover" src="${cover("Music")}"><div><b id="nowTitle">Ничего не играет</b><span id="nowArtist">Выбери трек</span></div></div><div class="controls"><div class="control-buttons"><button class="ctrl" id="prev">⏮</button><button class="ctrl play" id="play">▶</button><button class="ctrl" id="next">⏭</button></div><div class="progress"><span id="cur">0:00</span><input id="seek" type="range" min="0" max="100" value="0"><span id="dur">0:00</span></div></div><div class="volume">🔊 <input id="vol" type="range" min="0" max="1" step=".01" value=".8"></div></div><div id="authModal" class="modal hidden"></div>`;
 document.querySelector("#search").addEventListener("input",e=>renderTracks(e.target.value));
 document.querySelector("#play").onclick=()=>audio.paused?audio.play():audio.pause();document.querySelector("#prev").onclick=()=>changeTrack(-1);document.querySelector("#next").onclick=()=>changeTrack(1);document.querySelector("#seek").oninput=e=>{if(audio.duration)audio.currentTime=audio.duration*e.target.value/100};document.querySelector("#vol").oninput=e=>audio.volume=e.target.value;audio.volume=Number(localStorage.getItem("cander_volume")||.8);
 document.querySelector("#vol").value=audio.volume;audio.ontimeupdate=()=>{if(audio.duration){document.querySelector("#seek").value=audio.currentTime/audio.duration*100;document.querySelector("#cur").textContent=time(audio.currentTime)}};audio.onloadedmetadata=()=>document.querySelector("#dur").textContent=time(audio.duration);audio.onplay=()=>document.querySelector("#play").textContent="Ⅱ";audio.onpause=()=>document.querySelector("#play").textContent="▶";audio.onended=()=>changeTrack(1);audio.onvolumechange=()=>localStorage.setItem("cander_volume",audio.volume);
 updateAccountUI();
}
function updateAccountUI(){const el=document.querySelector("#account");if(!el)return;const s=getSession();el.innerHTML=s?`<div class="account"><span>${esc(s.name||s.email)}</span><button class="smallbtn" onclick="logout()">Выйти</button></div>`:`<button class="btn ghost" onclick="openAuth('login')">Войти</button><button class="btn accent" onclick="openAuth('register')">Регистрация</button>`}
function openAuth(mode="register"){const m=document.querySelector("#authModal");m.classList.remove("hidden");m.innerHTML=`<div class="modal-card"><button class="modal-close" onclick="closeAuth()">×</button><h2>${mode==="register"?"Регистрация":"Вход"}</h2><form id="authForm"><input id="authName" ${mode==="login"?"type=hidden":"required"} placeholder="Имя"><input id="authEmail" type="email" required placeholder="Почта Gmail"><input id="authPassword" type="password" minlength="6" required placeholder="Пароль (минимум 6 символов)"><div id="authError" class="form-error"></div><button class="btn accent" type="submit">${mode==="register"?"Создать аккаунт":"Войти"}</button></form><button class="auth-switch" onclick="openAuth('${mode==="register"?"login":"register"}')">${mode==="register"?"Уже есть аккаунт? Войти":"Нет аккаунта? Зарегистрироваться"}</button></div>`;document.querySelector("#authForm").onsubmit=e=>submitAuth(e,mode)}
function closeAuth(){document.querySelector("#authModal")?.classList.add("hidden")}
async function submitAuth(e,mode){e.preventDefault();const name=document.querySelector("#authName").value.trim(),email=document.querySelector("#authEmail").value.trim().toLowerCase(),password=document.querySelector("#authPassword").value,error=document.querySelector("#authError");error.textContent="";if(!validGmail(email)){error.textContent="Введите корректный адрес Gmail в формате name@gmail.com";return}if(password.length<6){error.textContent="Пароль должен содержать минимум 6 символов";return}if(mode==="register"&&!name){error.textContent="Введите имя";return}const existing=await getUser(email);if(mode==="register"){if(existing){error.textContent="Аккаунт с этой почтой уже существует";return}const user={email,name,passwordHash:await sha256(password),created:Date.now()};await saveUser(user);setSession(user);closeAuth();return}if(!existing||existing.passwordHash!==await sha256(password)){error.textContent="Неверная почта или пароль";return}setSession(existing);closeAuth()}
window.logout=()=>{setSession(null);location.reload()};
function time(n){return !isFinite(n)?"0:00":Math.floor(n/60)+":"+String(Math.floor(n%60)).padStart(2,"0")}
async function renderTracks(filter=""){let tracks=await allTracks();if(pageName==="favorites")tracks=tracks.filter(t=>t.favorite);const q=filter.toLowerCase().trim();if(q)tracks=tracks.filter(t=>(t.title+" "+t.artist).toLowerCase().includes(q));currentList=tracks;const box=document.querySelector("#trackContainer");if(!box)return;if(!tracks.length){box.innerHTML=`<div class="empty">Здесь пока пусто.<br><br><a class="btn accent" href="library.html">Добавить музыку</a></div>`;return}box.innerHTML=tracks.map(t=>`<div class="track"><img class="track-cover" src="${t.cover||cover(t.title)}"><div onclick="playTrack('${t.id}')" style="cursor:pointer"><div class="track-name">${esc(t.title)}</div><div class="track-artist">${esc(t.artist||"Неизвестный исполнитель")}</div></div><div class="track-actions"><button class="smallbtn heart ${t.favorite?"active":""}" onclick="toggleFav('${t.id}')">♥</button><button class="smallbtn" onclick="deleteSong('${t.id}')">×</button></div></div>`).join("")}
window.playTrack=async id=>{const tracks=await allTracks(),t=tracks.find(x=>x.id===id);if(!t)return;currentList=pageName==="favorites"?tracks.filter(x=>x.favorite):tracks;currentIndex=currentList.findIndex(x=>x.id===id);currentId=id;if(currentObjectUrl)URL.revokeObjectURL(currentObjectUrl);if(t.blob)currentObjectUrl=URL.createObjectURL(t.blob);else currentObjectUrl=t.url;audio.src=currentObjectUrl;await audio.play();document.querySelector("#nowTitle").textContent=t.title;document.querySelector("#nowArtist").textContent=t.artist||"Неизвестный исполнитель";document.querySelector("#nowCover").src=t.cover||cover(t.title)};
window.toggleFav=async id=>{const ts=await allTracks(),t=ts.find(x=>x.id===id);t.favorite=!t.favorite;await saveTrack(t);renderTracks(document.querySelector("#search").value)};
window.deleteSong=async id=>{if(currentId===id){audio.pause();audio.src=""}await deleteTrack(id);renderTracks(document.querySelector("#search").value);updateStats()};function changeTrack(delta){if(!currentList.length)return;currentIndex=(currentIndex+delta+currentList.length)%currentList.length;playTrack(currentList[currentIndex].id)}
async function updateStats(){const ts=await allTracks(),el=id=>document.getElementById(id);if(el("count"))el("count").textContent=ts.length;if(el("favcount"))el("favcount").textContent=ts.filter(t=>t.favorite).length}
async function addFiles(files){for(const f of files){if(!f.type.startsWith("audio/"))continue;const title=f.name.replace(/\.[^.]+$/,""),id=crypto.randomUUID();await saveTrack({id,title,artist:"Локальный файл",fileName:f.name,blob:f,cover:cover(title),favorite:false,added:Date.now()})}await renderTracks();updateStats()}
async function home(){layout(`<section class="hero"><div><h1>Твоя музыка.</h1><p>Личный музыкальный плеер. Добавляй свои аудиофайлы — они сохраняются прямо в браузере.</p><a class="btn accent" href="library.html">Открыть коллекцию</a></div></section><div class="section-title"><h2>Недавно добавленные</h2><a class="muted" href="library.html">Все песни →</a></div><div id="trackContainer" class="track-list"></div>`);await renderTracks()}
async function library(){layout(`<h1 class="page-title">Все песни</h1><p class="subtitle">Твоя локальная музыкальная коллекция</p><div class="drop" id="drop"><b>Добавь музыку</b><p class="muted">Перетащи MP3, WAV, OGG и другие аудиофайлы сюда</p><input id="files" type="file" accept="audio/*" multiple class="btn"></div><div class="section-title"><h2>Моя коллекция</h2><span id="count" class="muted">0</span></div><div id="trackContainer" class="track-list"></div>`);document.querySelector("#files").onchange=e=>addFiles(e.target.files);const d=document.querySelector("#drop");["dragenter","dragover"].forEach(x=>d.addEventListener(x,e=>{e.preventDefault();d.classList.add("drag")}));["dragleave","drop"].forEach(x=>d.addEventListener(x,e=>{e.preventDefault();d.classList.remove("drag")}));d.ondrop=e=>addFiles(e.dataTransfer.files);await renderTracks();updateStats()}
async function favorites(){layout(`<h1 class="page-title">Избранное</h1><p class="subtitle">Треки, которые ты отметил сердцем</p><div id="trackContainer" class="track-list"></div>`);await renderTracks()}
async function about(){layout(`<h1 class="page-title">Cander Music</h1><p class="subtitle">Твой небольшой локальный музыкальный сервис.</p><div class="stats"><div class="stat"><b id="count">0</b><span>треков</span></div><div class="stat"><b id="favcount">0</b><span>в избранном</span></div><div class="stat"><b>∞</b><span>без сервера</span></div></div><div class="notice">Музыка и локальные аккаунты хранятся в браузере через IndexedDB. Данные сохраняются после перезахода, но очистка данных сайта браузером их удалит.</div><h2>Что умеет сайт</h2><p class="muted">Главная, коллекция, поиск, избранное, воспроизведение, перемотка, громкость, загрузка музыки и локальная регистрация.</p>`);updateStats()}
(async()=>{await openDB();if(pageName==="home")home();else if(pageName==="library")library();else if(pageName==="favorites")favorites();else about()})();
